### ISSUE TITLE
Compatibility with FHist 0.11?

### ISSUE THREAD

**Issue by graeme-a-stewart** [peremato/EDM4hep.jl#8]
Currently EDM4hep has a package compat with FHist only for the 0.10 series. 

FHist 0.10.7 is only compatible with `Makie = "0.19, ^0.20.1"`, which then excludes the latest `0.21` series.

Is there a reason for this restriction? Could it be updated to 0.11 as well? i.e,

```
 FHist = "0.10, 0.11"
```

It's quite painful managing environments that want EDM4hep and the most recent version(s) of Makie right now.

**Comment by graeme-a-stewart** [comment]
Ping also to @Moelf in case there are other gotchas...

**Comment by Moelf** [comment]
0.11 has breaking change so you just gotta fix them I guess

**Comment by graeme-a-stewart** [comment]
Yeah, I fixed the `binedges` matter in #9. Is there a list of other things that were breaking changes from v0.10 to v.11?

**Comment by Moelf** [comment]
Constructor and the type of History{N}D are the only breaking changes you should observe I believe

**Comment by graeme-a-stewart** [comment]
I think it's ok then - I fixed the constructors and `History` isn't used AFAICS. Thanks!
